#!/bin/sh
set -e

TITLE="Surfshark"

cmd=$(printf "attack\ndown\nreset\nstatus" | dmenu -i -p "command")

[ "$cmd" = "reset" ] && cmd=attack\
                     && sudo surfshark-vpn down > /dev/null

res=$(echo "" | sudo surfshark-vpn $cmd | tail -n 3)

notify-send "$TITLE" "$res"
