#!/bin/sh
# A recursive dmenu menu.
# Copyright 2010-2013 Tom Vincent <http://tlvince.com/contact/>

DMENU="dmenu -i -m 0"

prefix="dmenu_"
cmd="$(dmenu_path | grep "$prefix" | grep -Ev "_menu|_path" | \
       sed "s/$prefix//" | $DMENU "$@")"
[ "$cmd" ] && "${SHELL:-/bin/sh}" -c "${prefix}$cmd &" &
