#!/bin/sh
set -e

DMENU="dmenu -i -m 0"

# manage locations cache to improve performance
cachedir="$HOME/.cache"
cache="$cachedir/windscribe_locations"
[ ! -e "$cachedir" ] && mkdir -p "$cachedir"
if ! locations=$(cat "$cache") ; then
    echo "no cache"
    locations=$(windscribe locations | tail -n+2 | cut -c 23-27 | sort -u)
    echo "$locations" > "$cache"
fi

cmd=$(printf "best\ndisconnect\nstatus\n$locations" | $DMENU -p "command")

if [ "$cmd" = "disconnect" ] || [ "$cmd" = "status" ] ; then
    res=$(windscribe $cmd | tail -n 1)
else
    res=$(windscribe connect $cmd | tail -n 1)
fi

notify-send "Windscribe" "$res"
