#!/bin/sh
set -e

TITLE="Surfshark"
DMENU="dmenu -i -m 0"

cmd=$(printf "attack\ndown\nreset\nstatus" | $DMENU -p "command")

[ "$cmd" = "reset" ] && cmd=attack\
                     && sudo surfshark-vpn down > /dev/null

res=$(echo "" | sudo surfshark-vpn $cmd | tail -n 3)

notify-send "$TITLE" "$res"
