#!/bin/sh
set -e

DMENU="dmenu -i -m 0"

cmd=$(printf "connect\ndisconnect\nreconnect\nstatus" | $DMENU -p "command")
[ "$cmd" = "connect" ] && cmd="$cmd -f"

res=$(sudo protonvpn $cmd | tail -n3)
notify-send "ProtonVPN" "$res"
