#!/bin/sh

TITLE="Bitwarden"
CLEAR_TIME=10

# generate a list login service with id and name
list=$(bw list items \
      | grep  -Eo '"id":"[^"]+"[^}]+"type":1[^}]+"name":"[^"]+"' \
      | sed 's/"id":"\([^"]*\)".*"name":"\([^"]*\)".*/\1\t\2/')

# select service id with dmenu
name=$(printf "$list" | awk -F'\t' '{print $2}' | dmenu -i)
id=$(printf "$list" | grep "$name" | head -n1 | awk -F'\t' '{print $1}')

# get password
if ! pass=$(bw get password "$id") ; then
  notify-send "$TITLE" "fail"
  exit 1
fi

# copy password
printf "$pass" | xclip -selection clipboard
notify-send "$TITLE" "password copy"

# clear clipboard after 10 seconds
sh -c "sleep \"$CLEAR_TIME\" ; printf \"\" | xclip -selection clipboard ;\
       notify-send \"$TITLE\" \"clipboard clear\""&

