#!/bin/sh
set -e

# TODO: add cache
locations=$(windscribe locations | tail -n+2 | cut -c 17-20 | sort -u)

cmd=$(printf "$locations\nbest\ndisconnect\nstatus" | dmenu -i -p "command")

if [ "$cmd" = "disconnect" ] || [ "$cmd" = "status" ] ; then
    res=$(windscribe $cmd | tail -n 1)
else
    res=$(windscribe connect $cmd | tail -n 1)
fi

notify-send "Windscribe" "$res"

