#!/bin/sh
set -e

TITLE="Bitwarden"
CLEAR_TIME=10

# dmenu prompt
pass=$(bw list items | grep -Eo '"name":"[[:alnum:] ]+"' | awk -F: -F\" '{print $4}' | dmenu -i | xargs bw get password)
if [ $? -ne 0 ] ; then
  notify-send "$TITLE" "fail"
  exit 1
fi

# copy password
printf "$pass" | xclip -selection clipboard
notify-send "$TITLE" "password copy"

# clear clipboard after 10 seconds
sh -c "sleep \"$CLEAR_TIME\" ; printf \"\" | xclip -selection clipboard ; notify-send \"$TITLE\" \"clipboard clear\""&

